volume up: key(volup)
volume down: key(voldown)
set volume <number>: user.media_set_volume(number)
media mute: key(mute)
media next: key(next)
media previous: key(prev)
media (play | pause): key(play)
