version: "3"

tasks:
  upload-cheatsheet:
    desc: '.'
    cmds:
      - echo "mimic('cheat sheet')" |/Users/maciek/.talon/.venv/bin/repl 
      - algolia deleteindicespattern -a TSMFGMK167 -k `doppler secrets get --plain ALGOLIA_API_KEY -p casa-del-maciek -c dev_maciej` -r 'talon' -x false 
      - algolia i -s /Users/maciek/.talon/user/knausj_talon/maciek/cheatsheet.json  -a TSMFGMK167 -k `doppler secrets get --plain ALGOLIA_API_KEY -p casa-del-maciek -c dev_maciej`  -n talon 

  deploy:
    desc: "."
    cmds:
      - rsync -avz --delete --exclude=.git --exclude=maciek/experimental --exclude=.venv ~/projects/knausj_talon/ ~/.talon/user/knausj_talon
      - rsync -avz --delete --exclude=.git cursorless-settings ~/.talon/user/
  deploy-windows:
    desc: "."
    cmds:
      -  robocopy 'C:\Users\maciej.klimek\projects\knausj_talon' 'C:\Users\maciej.klimek\AppData\Roaming\talon\user\' /e /xf .git /xf maciek/experimental /xf .venv
  pandoc:
    desc: "."
    cmds:
      - pandoc -s ~/.talon/user/knausj_talon/maciek/cheatsheet.md -c maciek/cheatsheet.css -f markdown-raw_html -t html -o cheatsheet.html
      - pandoc -s ~/.talon/user/knausj_talon/maciek/cheatsheet_shorter.md -c maciek/cheatsheet.css -f markdown-raw_html -t html -o cheatsheet_shorter.html
  show-cheatsheet:
    desc: "."
    cmds:
      - /opt/homebrew/bin/fish -c "google-chrome cheatsheet.html"
