version: "3"

tasks:
  
  upload-cheatsheet:
    desc: '.'
    cmds:
      - echo "mimic('wake up')"
      - echo "mimic('cheat sheet')" |/Users/maciek/.talon/.venv/bin/repl 
      - algolia indices clear talon -y 
      - algolia objects import talon -F /Users/maciek/.talon/user/knausj_talon/maciek/cheatsheet.ndjson
      # Previous CLI I was using is DEPRECATED 
      # - algolia deleteindicespattern -a TSMFGMK167 -k `doppler secrets get --plain ALGOLIA_API_KEY -p casa-del-maciek -c dev_maciej` -r 'talon' -x false 
      # - algolia i -s /Users/maciek/.talon/user/knausj_talon/maciek/cheatsheet.json  -a TSMFGMK167 -k `doppler secrets get --plain ALGOLIA_API_KEY -p casa-del-maciek -c dev_maciej`  -n talon 

  deploy:
    desc: "."
    cmds:
      - rsync -avz --delete --exclude=.git --exclude=maciek/experimental --exclude=.venv ~/projects/knausj_talon/ ~/.talon/user/knausj_talon
      - rsync -avz --delete --exclude=.git cursorless-settings ~/.talon/user/
  pandoc:
    desc: "."
    cmds:
      - pandoc -s ~/.talon/user/knausj_talon/maciek/cheatsheet.md -c maciek/cheatsheet.css -f markdown-raw_html -t html -o cheatsheet.html
      - pandoc -s ~/.talon/user/knausj_talon/maciek/cheatsheet_shorter.md -c maciek/cheatsheet.css -f markdown-raw_html -t html -o cheatsheet_shorter.html
  show-cheatsheet:
    desc: "."
    cmds:
      - /opt/homebrew/bin/fish -c "google-chrome cheatsheet.html"
