version: "3"
tasks:
  deploy:
    desc: "."
    cmds:
      - rsync -avz --delete ~/projects/knausj_talon/ ~/.talon/user/knausj_talon
  pandoc:
    desc: "."
    cmds:
      - pandoc -s ~/.talon/user/knausj_talon/maciek/cheatsheet.md -c maciek/cheatsheet.css -f markdown-raw_html -t html -o cheatsheet.html
  show-cheatsheet:
    desc: "."
    cmds:
      - google-chrome-unstable cheatsheet.html
